version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: campaign-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: campaigns_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: campaign-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/campaigns_db
    command: ["node", "dist/main.js"]

volumes:
  pgdata:
