version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: campaign-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: campaign-manager
      POSTGRES_DB: campaigns_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d campaigns_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: campaign-app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/campaigns_db
      NODE_ENV: production
      TYPEORM_SYNCHRONIZE: true
      TYPEORM_LOGGING: true
      TYPEORM_AUTO_LOAD_ENTITIES: true
      TYPEORM_ENTITIES: dist/**/*.entity.js
      TYPEORM_MIGRATIONS: dist/**/migrations/*.js
    command: ["node", "dist/src/main.js"]

volumes:
  pgdata: