version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: campaign-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: campaigns_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: campaign-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/campaigns_db
      TYPEORM_HOST: localhost
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: user
      TYPEORM_PASSWORD: password
      TYPEORM_DATABASE: campaigns_db
      TYPEORM_SYNCHRONIZE: true
      TYPEORM_LOGGING: true
      TYPEORM_AUTO_LOAD_ENTITIES: true
      TYPEORM_ENTITIES: dist/**/*.entity.js
      TYPEORM_MIGRATIONS: dist/**/migrations/*.js
    command: ["node", "dist/main.js"]

volumes:
  pgdata:
